# Generated by Django 5.2.12 on 2026-03-22 06:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-fecha', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('nit_ruc', models.CharField(max_length=32, unique=True)),
                ('email_contacto', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_evaluacion', to='competition.evento')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CategoriaRitmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_ritmo', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('solista', 'Solista'), ('pareja', 'Pareja'), ('grupo', 'Grupo')], max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_ritmo', to='competition.evento')),
            ],
            options={
                'ordering': ('nombre_ritmo', 'modalidad'),
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_acto', models.CharField(max_length=150)),
                ('estado_pago', models.BooleanField(default=False)),
                ('puntaje_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('categoria_ritmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='competition.categoriaritmo')),
            ],
            options={
                'ordering': ('nombre_acto',),
            },
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jueces', to='competition.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_como_juez', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('evento', 'usuario'),
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('comentario', models.TextField(blank=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='competition.criterioevaluacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='competition.inscripcion')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='competition.juez')),
            ],
            options={
                'ordering': ('inscripcion', 'criterio', 'juez'),
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='competition.organizador'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=32)),
                ('edad', models.PositiveSmallIntegerField()),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='competition.inscripcion')),
            ],
            options={
                'ordering': ('nombre_completo',),
            },
        ),
        migrations.AddConstraint(
            model_name='criterioevaluacion',
            constraint=models.UniqueConstraint(fields=('evento', 'nombre'), name='uq_criterio_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='categoriaritmo',
            constraint=models.UniqueConstraint(fields=('evento', 'nombre_ritmo', 'modalidad'), name='uq_categoria_ritmo_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('categoria_ritmo', 'nombre_acto'), name='uq_inscripcion_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='juez',
            constraint=models.UniqueConstraint(fields=('usuario', 'evento'), name='uq_juez_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('juez', 'inscripcion', 'criterio'), name='uq_calificacion_por_juez_inscripcion_criterio'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(fields=('organizador', 'nombre', 'fecha'), name='uq_evento_por_organizador'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'identificacion'), name='uq_participante_por_inscripcion'),
        ),
    ]
