# Generated by Django 6.0.3 on 2026-03-23 06:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def generar_slugs(apps, schema_editor):
    Evento = apps.get_model("competition", "Evento")
    for evento in Evento.objects.filter(slug=""):
        base = slugify(f"{evento.nombre}-{evento.fecha}")
        evento.slug = f"{base}-{str(uuid.uuid4())[:8]}"
        evento.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Agregar slug SIN unique para evitar conflicto con filas existentes
        migrations.AddField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, default=""),
            preserve_default=False,
        ),
        # 2. Poblar slugs de registros existentes
        migrations.RunPython(generar_slugs, migrations.RunPython.noop),
        # 3. Ahora sí agregar la restricción de unicidad
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        # 4. Agregar campo usuario a Organizador
        migrations.AddField(
            model_name='organizador',
            name='usuario',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organizador',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
