# Generated by Django 6.0.3 on 2026-03-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_participante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='feedback_audio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categoriaritmo',
            name='edad_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriaritmo',
            name='edad_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='academia',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='comprobante_categoria_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado_inscripcion',
            field=models.CharField(choices=[('pendiente', 'Pendiente validación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='foto_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='pista_musical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='competition.evento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipanteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=32)),
                ('edad', models.PositiveSmallIntegerField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('comprobante_pago_url', models.URLField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente_validacion', 'Pendiente de validación'), ('activo', 'Activo'), ('rechazado', 'Rechazado')], default='pendiente_validacion', max_length=25)),
                ('nota_rechazo', models.TextField(blank=True, default='')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_generales', to='competition.evento')),
            ],
            options={
                'ordering': ('nombre_completo',),
            },
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('representante', models.CharField(max_length=150)),
                ('cedula_representante', models.CharField(max_length=32)),
                ('academia', models.CharField(blank=True, default='', max_length=150)),
                ('inscripcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pareja', to='competition.inscripcion')),
                ('participante_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parejas_como_1', to='competition.participantegeneral')),
                ('participante_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parejas_como_2', to='competition.participantegeneral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('representante', models.CharField(max_length=150)),
                ('cedula_representante', models.CharField(max_length=32)),
                ('academia', models.CharField(blank=True, default='', max_length=150)),
                ('inscripcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='competition.inscripcion')),
                ('participantes', models.ManyToManyField(blank=True, related_name='grupos', to='competition.participantegeneral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=15)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='competition.evento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField()),
                ('duracion_segundos', models.PositiveSmallIntegerField(default=180)),
                ('tiempo_extra', models.PositiveSmallIntegerField(default=0, help_text='Segundos extra por falla técnica')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='competition.cronograma')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_cronograma', to='competition.inscripcion')),
            ],
            options={
                'ordering': ('cronograma', 'orden'),
                'constraints': [models.UniqueConstraint(fields=('cronograma', 'orden'), name='uq_orden_por_cronograma')],
            },
        ),
        migrations.AddConstraint(
            model_name='participantegeneral',
            constraint=models.UniqueConstraint(fields=('evento', 'cedula'), name='uq_participante_general_por_evento'),
        ),
    ]
