# Generated by Django 6.0.3 on 2026-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_fase3_participante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizador',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='organizador',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
