# Generated by Django 6.0.3 on 2026-03-24 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_empresa_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='org_miembros', to=settings.AUTH_USER_MODEL),
        ),
    ]
