# Generated by Django 6.0.3 on 2026-03-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_equipo_miembros'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemcronograma',
            name='uq_orden_por_cronograma',
        ),
        migrations.AddField(
            model_name='itemcronograma',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemcronograma',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcronograma',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcronograma',
            name='responsable',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='itemcronograma',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='itemcronograma',
            name='duracion_segundos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcronograma',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_cronograma', to='competition.inscripcion'),
        ),
        migrations.AlterField(
            model_name='itemcronograma',
            name='tiempo_extra',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
