# Generated by Django 5.2.12 on 2026-03-25 21:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_cronograma_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaritmo',
            name='precio_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion_portal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evento',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='portal_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='participante_solista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_solista', to='competition.participantegeneral'),
        ),
        migrations.AddField(
            model_name='itemcronograma',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='competition.evento')),
            ],
            options={
                'ordering': ('fecha', 'hora_inicio'),
            },
        ),
        migrations.CreateModel(
            name='FullPassConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(default='Full Pass', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('es_requerido', models.BooleanField(default=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_pass_config', to='competition.evento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoFullPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cedula', models.CharField(max_length=32)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('comprobante_imagen', models.ImageField(blank=True, null=True, upload_to='comprobantes/full_pass/')),
                ('numero_comprobante', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('nota_rechazo', models.TextField(blank=True, default='')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_full_pass', to='competition.evento')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PagoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprobante_imagen', models.ImageField(blank=True, null=True, upload_to='comprobantes/categorias/')),
                ('numero_comprobante', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('nota_rechazo', models.TextField(blank=True, default='')),
                ('inscripcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_categoria', to='competition.inscripcion')),
                ('pago_full_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_categoria', to='competition.pagofullpass')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrdenRitmoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ritmo', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('solista', 'Solista'), ('pareja', 'Pareja'), ('grupo', 'Grupo')], max_length=20)),
                ('orden', models.PositiveSmallIntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_ritmo', to='competition.evento')),
            ],
            options={
                'ordering': ('evento', 'orden'),
                'constraints': [models.UniqueConstraint(fields=('evento', 'ritmo', 'modalidad'), name='uq_orden_ritmo_por_evento')],
            },
        ),
        migrations.AddConstraint(
            model_name='pagofullpass',
            constraint=models.UniqueConstraint(fields=('evento', 'cedula'), name='uq_pago_full_pass_por_evento'),
        ),
    ]
