# Generated by Django 5.2.12 on 2026-03-27 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_evento_multimodalidad_categoria_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='aviso_privacidad_corto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='politica_privacidad_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='politica_privacidad_version',
            field=models.CharField(blank=True, default='2026-03', max_length=40),
        ),
        migrations.CreateModel(
            name='ConsentimientoDatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flujo', models.CharField(choices=[('registro_general', 'Registro general'), ('full_pass', 'Full Pass'), ('inscripcion_categoria', 'Inscripción de categoría')], max_length=40)),
                ('version_politica', models.CharField(max_length=40)),
                ('politica_privacidad_url', models.URLField(blank=True, default='')),
                ('aviso_privacidad', models.TextField(blank=True, default='')),
                ('titular_nombre', models.CharField(max_length=150)),
                ('titular_documento', models.CharField(max_length=32)),
                ('titular_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('es_menor_edad', models.BooleanField(default=False)),
                ('aceptado_por_representante', models.BooleanField(default=False)),
                ('nombre_representante_legal', models.CharField(blank=True, default='', max_length=150)),
                ('cedula_representante_legal', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_datos', to='competition.evento')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_datos', to='competition.inscripcion')),
                ('pago_full_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_datos', to='competition.pagofullpass')),
                ('participante_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_datos', to='competition.participantegeneral')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
