# Generated by Django 5.2.12 on 2026-03-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_organizador_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email_provider',
            field=models.CharField(choices=[('smtp', 'SMTP personalizado'), ('gmail_app', 'Gmail (App Password)')], default='smtp', help_text='Proveedor de correo: SMTP personalizado o Gmail con App Password.', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='gmail_app_password',
            field=models.CharField(blank=True, default='', help_text='Clave de Google tipo App Password para pruebas.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='gmail_sender_email',
            field=models.EmailField(blank=True, default='', help_text='Correo de Gmail para pruebas (ej: tucorreo@gmail.com)', max_length=254),
        ),
    ]
